### ISSUE TITLE
Sleep in lib.rs example

### ISSUE THREAD

**Issue by thinkier** [C4K3/ozelot#1]
Currently `lib.rs` doesn’t have any mention of needing to sleep in the loop, might be a good idea add that so new users can be aware of it. `examples/` is fine though. Otherwise, solid library.

**Comment by C4K3** [comment]
Oh in the example? Yeah that's probably a good idea. If you want, you're very welcome to change it yourself and send a PR, otherwise I'll do it when I have time.

I started on a more complete example using mio, but never finished it. Hopefully I'll get that done soon.
