### ISSUE TITLE
Multi-version support

### ISSUE THREAD

**Issue by zebp** [C4K3/ozelot#10]
Hi, I'm current evaluating libraries that implement the minecraft protocol for a project I want to work on and I was really excited when I saw this. Sadly my project needs to be able to connect to different protocol versions, is there any plan to add a way to specify which protocol the client can use?

**Comment by C4K3** [comment]
The way the library is written right now the version is hardcoded. Somebody did discuss the possibility of supporting multiple versions, but I can't find the issue (perhaps it was on irc.) I don't think it would require any massive changes to support multiple versions at once, I think it's a very doable thing.

Unfortunately I don't have too much time to work on it right now, but if it's something you (or others) would like to work on, I'd totally support that.

**Comment by Lucky4Luuk** [comment]
Any update on this? This is over a year ago and multi-versioning still doesn't seem to be here, but it would be a great feature!
