### ISSUE TITLE
Expose deserialization methods as public.

### ISSUE THREAD

**Issue by cedws** [C4K3/ozelot#7]
Hi there. I would like to use Ozelot as a library for an experimental server project. It seems that packets such as `ozelot::serverbound::Handshake` do not expose `deserialize` as public. Is there a reason for this?

**Comment by C4K3** [comment]
There's no real reason besides I don't have any use for them being public. If you do have a use for them being public, then I see no reason we couldn't just make them public.

**Comment by cedws** [comment]
Great! Please take a look at my PR when you have the time. I really like the way you use Clojure to do the codegen.
